name: Automated sanity tests.

on: [push, pull_request]

jobs:
  video-exists-test:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Get changed files.
        id: changed-files
        uses: tj-actions/changed-files@v22.1

      - name: TMP list all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed!!!"
          done

      #- name: TEMP check if List.md changed...
      #  if: contains(steps.changed-files.outputs.modified_files, 'List.md')
      #  run: echo List modified!

      # get modified lines
      # extract new URLs and store them in list
      # Execute pytest foreach new url 

      #- name: Verify URL is valid and video exists.
      #  run: |
      #    pytest tests/test_video_exists.py --video_url="%%%"
